import asyncio
import json
import logging
from collections.abc import AsyncGenerator
from datetime import UTC, datetime
from typing import TYPE_CHECKING

import pyarrow as pa
from docling_core.types.doc.document import DescriptionMetaField, PictureMeta
from lancedb.pydantic import LanceModel

from haiku.rag.client.documents import (
    check_source_accessible,
    chunk_document,
    create_document_from_source,
)
from haiku.rag.client.session import SingleDatabaseSession
from haiku.rag.client.titles import generate_title
from haiku.rag.converters import get_converter
from haiku.rag.store.compression import compress_docling_split
from haiku.rag.store.engine import REBUILD_COMMANDS
from haiku.rag.store.models.chunk import Chunk
from haiku.rag.store.models.document import Document
from haiku.rag.store.models.document_item import DocumentItem, extract_items
from haiku.rag.store.repositories.settings import SettingsRepository
from haiku.rag.store.schema import (
    INCOMPLETE_REBUILD_TABLE,
    ChunkRecordBase,
    IncompleteRebuildRecord,
    create_chunk_model,
    ensure_indexes,
)

if TYPE_CHECKING:
    from docling_core.types.doc.document import DoclingDocument

    from haiku.rag.client import RebuildMode

logger = logging.getLogger(__name__)

_REBUILD_BATCH_SIZE = 50
_ITEMS_WRITE_BYTES = 16 << 20
_STAGING_TABLE_NAME = "chunks_rebuild_staging"
_STAGING_MARKER_TABLE_NAME = "chunks_rebuild_marker"
_STAGING_COPY_BATCH_SIZE = 1000
_DESCRIPTION_COLUMNS = ("docling_document", "docling_version")
_FULL_FALLBACK_COLUMNS = ("docling_document", "docling_pages", "docling_version")


class _StagingChunkRecord(LanceModel):
    """Non-vector copy of a chunk row, used by ``_rebuild_embed_only``.

    The staging table holds the original chunks' identity and content while
    the live ``chunks`` table is dropped and recreated with a potentially
    different vector dimension. The vector itself is omitted — re-embedding
    is the whole point — and ``content_fts`` is regenerated by
    ``contextualize`` during phase 2.

    Mirrors ``ChunkRecordBase`` minus ``content_fts`` and ``vector``. Keep
    in sync: ``test_staging_chunk_record_mirrors_chunk_record_schema``
    enforces parity so a new column on ``ChunkRecordBase`` can't silently
    get dropped on every embed-only rebuild.
    """

    id: str
    document_id: str
    content: str
    metadata: str
    order: int


class _StagingMarkerRecord(LanceModel):
    """Sentinel marking the staging table as complete.

    The marker table is created only after ``_populate_staging_table`` writes
    every chunk into staging. Its presence at the top of a rebuild means
    phase 2 (the embed loop) was interrupted by an earlier crash, so staging
    is the authoritative source for the original chunk identities and we
    must resume from it instead of rerunning phase 1.
    """

    id: str


async def rebuild_database(
    session: SingleDatabaseSession, mode: "RebuildMode"
) -> AsyncGenerator[str, None]:
    """Rebuild the database with the specified mode.

    Yields the ID of each document: FULL, RECHUNK and DESCRIPTIONS once its
    batch is written, EMBED_ONLY before writing it.

    Holds the store's rebuild lock for the whole run so tag operations fail
    fast instead of snapshotting a half-rebuilt database. The lock is held
    across yields; an abandoned generator releases it when closed or
    garbage-collected.
    """
    from haiku.rag.client import RebuildMode

    async with session.store._rebuild_lock:
        # Every mode writes.
        session.store._assert_writable()
        if mode == RebuildMode.SET_EMBEDDER:
            await _set_embedder(session)
            return
        if mode == RebuildMode.REINDEX:
            await session.store.rebuild_indexes()
            return

        async for doc_id in _rebuild_locked(session, mode):
            yield doc_id


async def _rebuild_locked(
    session: SingleDatabaseSession, mode: "RebuildMode"
) -> AsyncGenerator[str, None]:
    from haiku.rag.client import RebuildMode

    if (
        mode == RebuildMode.DESCRIPTIONS
        and session.config.processing.pictures != "description"
    ):
        raise ValueError(
            "rebuild --descriptions requires processing.pictures = 'description' "
            "in your config."
        )

    unfinished = await _incomplete_rebuild(session)
    if (
        mode == RebuildMode.EMBED_ONLY
        and unfinished is not None
        and unfinished.mode != mode.value
    ):
        command = REBUILD_COMMANDS[unfinished.mode]
        raise ValueError(
            f"An interrupted 'haiku-rag {command}' left documents without "
            f"chunks, which --embed-only cannot write. Run 'haiku-rag {command}' "
            "to finish it."
        )

    # Wait for any already-scheduled background vacuum before the first table
    # write. Rebuild rewrites rows, recreates tables and creates indices; a
    # concurrent optimize on the same table fails with "CreateIndex
    # transaction was preempted" from lance. Note: FULL calls
    # create_document_from_source inside its loop, which may schedule *new*
    # background vacuums — those run once the rebuild is under way and are fine.
    await session.drain_vacuum()

    # The chunks table is recreated when the vector dimension changes and by
    # EMBED_ONLY, which drops its vector index. Otherwise it keeps its rows and
    # index and the rebuild replaces them a batch at a time.
    incomplete = IncompleteRebuildRecord(
        mode=mode.value,
        vector_index=await _has_vector_index(session)
        or (unfinished is not None and unfinished.vector_index),
    )
    if unfinished is not None and mode in (
        RebuildMode.FULL,
        RebuildMode.RECHUNK,
        RebuildMode.DESCRIPTIONS,
    ):
        # The record names a mode that can finish the job. Once this one
        # discards EMBED_ONLY's staging copy below, EMBED_ONLY cannot.
        await _record_incomplete_rebuild(session, incomplete)

    # Resolve any leftover staging/marker tables from a previously
    # interrupted rebuild. Returns True only when phase 1 was already
    # complete and the current mode is EMBED_ONLY, in which case we resume
    # phase 2 from the existing staging table instead of recopying.
    resume_from_staging = await _resolve_rebuild_recovery(session, mode)

    table_dim = await _chunks_vector_dim(session)
    keeps_dimension = table_dim == session.store.embedder.vector_dim
    if keeps_dimension:
        # A run stopped between recreating the table at a new dimension and
        # recording it leaves the old one recorded, and the chunk model it
        # opens with is of that width.
        session.store.ChunkRecord = create_chunk_model(table_dim)

    # Light listing — id/uri/title/metadata only. Each rebuild function
    # fetches content and blobs one document at a time.
    documents = await session.list_documents(include_content=False)

    if mode == RebuildMode.TITLE_ONLY:
        async for doc_id in _rebuild_title_only(session, documents):
            yield doc_id
    elif mode == RebuildMode.EMBED_ONLY:
        async for doc_id in _rebuild_embed_only(
            session,
            documents,
            incomplete,
            resume_from_staging=resume_from_staging,
        ):
            yield doc_id
    elif mode == RebuildMode.RECHUNK:
        if not keeps_dimension:
            await _recreate_chunks_table(session, incomplete)
        async for doc_id in _rebuild_rechunk(session, documents):
            yield doc_id
    elif mode == RebuildMode.DESCRIPTIONS:
        if not keeps_dimension:
            await _recreate_chunks_table(session, incomplete)
        async for doc_id in _rebuild_descriptions(session, documents):
            yield doc_id
    else:  # FULL
        if not keeps_dimension:
            await _recreate_chunks_table(session, incomplete)
        async for doc_id in _rebuild_full(session, documents):
            yield doc_id

    if mode != RebuildMode.TITLE_ONLY:
        # The settings record the embedder whose vectors the chunks table
        # holds. A table the rebuild kept has the old embedder's vectors until
        # the loop ends, so an interrupted run keeps it recorded and a writable
        # open refuses the mix. TITLE_ONLY writes no vectors and records nothing.
        await SettingsRepository(session.store).save_current_settings()
        await session.store.rebuild_indexes()
        if incomplete.vector_index:
            await session.store._ensure_vector_index()
        await _clear_incomplete_rebuild(session)

    # Final maintenance if auto_vacuum enabled. Swallowing only so that a
    # failed post-rebuild optimize doesn't mask a successful rebuild — but
    # log it so the failure is visible in the output.
    if session.config.storage.auto_vacuum:
        try:
            await session.store.vacuum()
        except Exception:
            logger.warning("Post-rebuild vacuum failed", exc_info=True)


async def _set_embedder(session: SingleDatabaseSession) -> None:
    """Adopt the current embedder identity without re-embedding.

    Only valid while the stored vectors stay usable: the vector dimension and
    the prefixes must be unchanged. Either change needs re-embedding.
    """
    from haiku.rag.store.engine import EmbedderIdentity
    from haiku.rag.store.exceptions import ConfigMismatchError

    settings_repo = SettingsRepository(session.store)
    recorded = EmbedderIdentity.recorded_in(await settings_repo.get_current_settings())
    current = session.config.embeddings.model

    if recorded is not None:
        if (
            recorded.vector_dim is not None
            and recorded.vector_dim != current.vector_dim
        ):
            raise ConfigMismatchError(
                f"Stored vector dimension {recorded.vector_dim} differs from current "
                f"{current.vector_dim}; embeddings must be regenerated. "
                "Run 'haiku-rag rebuild'."
            )
        if (recorded.query_prefix, recorded.document_prefix) != (
            current.query_prefix,
            current.document_prefix,
        ):
            raise ConfigMismatchError(
                "Stored query/document prefixes differ from the configured ones. "
                "Run 'haiku-rag rebuild --embed-only' to re-embed."
            )

    await settings_repo.save_current_settings()


async def _hydrate(
    session: SingleDatabaseSession, light_docs: list[Document]
) -> AsyncGenerator[Document, None]:
    """Yield documents with content and docling structure, never page images.

    Documents that disappeared between listing and processing are skipped.
    """
    repo = session.document_repository
    for light_doc in light_docs:
        assert light_doc.id is not None
        doc = await repo.get_by_id(light_doc.id)
        structure = await repo.get_docling_data(light_doc.id)
        if doc is None or structure is None:
            continue
        doc.docling_document = structure.docling_document
        doc.docling_version = structure.docling_version
        yield doc


async def _rebuild_title_only(
    session: SingleDatabaseSession, documents: list[Document]
) -> AsyncGenerator[str, None]:
    """Generate titles for documents that don't have one."""
    repo = session.document_repository
    untitled = [d for d in documents if d.title is None]
    pending: list[Document] = []
    async for doc in _hydrate(session, untitled):
        assert doc.id is not None
        try:
            title = await generate_title(session.config, doc)
        except Exception:
            logger.warning(
                "Failed to generate title for document %s", doc.id, exc_info=True
            )
            continue
        if title is not None:
            doc.title = title
            pending.append(doc)
            if len(pending) >= _REBUILD_BATCH_SIZE:
                for saved in await repo.update_meta_all(pending):
                    assert saved.id is not None
                    yield saved.id
                pending = []
    for saved in await repo.update_meta_all(pending):
        assert saved.id is not None
        yield saved.id


async def _has_vector_index(session: SingleDatabaseSession) -> bool:
    """Whether the chunks table exists and carries a vector index."""
    if "chunks" not in (await session.store.db.list_tables()).tables:
        return False
    return any(
        "vector" in index.columns
        for index in await session.store.chunks_table.list_indices()
    )


async def _incomplete_rebuild(
    session: SingleDatabaseSession,
) -> IncompleteRebuildRecord | None:
    db = session.store.db
    if INCOMPLETE_REBUILD_TABLE not in (await db.list_tables()).tables:
        return None
    table = await db.open_table(INCOMPLETE_REBUILD_TABLE)
    rows = (await table.query().select(["mode", "vector_index"]).to_arrow()).to_pylist()
    return IncompleteRebuildRecord(**rows[0])


async def _record_incomplete_rebuild(
    session: SingleDatabaseSession, record: IncompleteRebuildRecord
) -> None:
    """Write the record, replacing any other, in one version of its table."""
    existing = await _incomplete_rebuild(session)
    if existing == record:
        return
    # lance warns when an overwrite creates the table.
    await session.store.db.create_table(
        INCOMPLETE_REBUILD_TABLE,
        data=[record],
        schema=IncompleteRebuildRecord,
        mode="create" if existing is None else "overwrite",
    )


async def _clear_incomplete_rebuild(session: SingleDatabaseSession) -> None:
    db = session.store.db
    if INCOMPLETE_REBUILD_TABLE in (await db.list_tables()).tables:
        await db.drop_table(INCOMPLETE_REBUILD_TABLE)


async def _recreate_chunks_table(
    session: SingleDatabaseSession, incomplete: IncompleteRebuildRecord
) -> None:
    """Recreate the chunks table empty at the configured vector dimension.

    The rebuild is recorded as incomplete first. No vector of the old embedder
    is left, so the settings record the configured one right away.
    """
    await _record_incomplete_rebuild(session, incomplete)
    await session.store.recreate_embeddings_table()
    await SettingsRepository(session.store).save_current_settings()


async def _chunks_vector_dim(session: SingleDatabaseSession) -> int:
    """The width of the chunks table's vector column, which the settings can
    disagree with after an interrupted rebuild."""
    schema = await session.store.chunks_table.schema()
    return schema.field("vector").type.list_size


async def _resolve_rebuild_recovery(
    session: SingleDatabaseSession, mode: "RebuildMode"
) -> bool:
    """Resolve any partially-completed rebuild state from a previous crash.

    Returns ``True`` if ``_rebuild_embed_only`` should resume from the
    existing staging table (phase 1 was already complete). In all other
    cases stale recovery tables are dropped and the rebuild starts fresh.

    State at entry           → action
    --------------------------------
    no staging, no marker    → return False (normal start)
    staging only             → drop staging (phase 1 was interrupted; ``chunks`` is intact)
    marker only              → drop marker (corrupted state)
    staging + marker, embed  → return True (resume phase 2 from staging)
    staging + marker, other  → drop both (staging is for embed-only; user picked a different mode)

    TITLE_ONLY writes no chunks and leaves every state for a later rebuild.
    """
    from haiku.rag.client import RebuildMode

    if mode == RebuildMode.TITLE_ONLY:
        return False

    db = session.store.db
    tables = (await db.list_tables()).tables
    has_staging = _STAGING_TABLE_NAME in tables
    has_marker = _STAGING_MARKER_TABLE_NAME in tables

    if not has_staging and not has_marker:
        return False

    if has_marker and not has_staging:
        logger.warning(
            "Found '%s' without staging table; dropping orphaned marker.",
            _STAGING_MARKER_TABLE_NAME,
        )
        await db.drop_table(_STAGING_MARKER_TABLE_NAME)
        return False

    if not has_marker:
        logger.warning(
            "Dropping incomplete '%s' from an interrupted phase 1.",
            _STAGING_TABLE_NAME,
        )
        await db.drop_table(_STAGING_TABLE_NAME)
        return False

    # has_staging and has_marker
    if mode == RebuildMode.EMBED_ONLY:
        logger.warning(
            "Resuming interrupted embed-only rebuild: phase 2 will run from "
            "existing '%s'.",
            _STAGING_TABLE_NAME,
        )
        return True

    logger.warning(
        "Dropping staging tables from a prior embed-only rebuild — current "
        "mode (%s) does not consume them.",
        mode.name,
    )
    await db.drop_table(_STAGING_MARKER_TABLE_NAME)
    await db.drop_table(_STAGING_TABLE_NAME)
    return False


async def _populate_staging_table(session: SingleDatabaseSession) -> None:
    """Stream the non-vector columns of the chunks table into staging.

    Uses ``to_batches`` for a single streaming read (no offset/limit
    pagination drift), so peak memory stays bounded regardless of corpus
    size. The vector column is omitted — the point of embed-only rebuild is
    to regenerate it.

    Requires ``_resolve_rebuild_recovery`` to have cleared any leftover
    staging table first: ``create_table`` raises if the name is already taken.
    """
    db = session.store.db
    tables = (await db.list_tables()).tables

    staging = await db.create_table(_STAGING_TABLE_NAME, schema=_StagingChunkRecord)
    if "chunks" not in tables:
        return

    stream = (
        await session.store.chunks_table.query()
        .select(["id", "document_id", "content", "metadata", "order"])
        .to_batches(max_batch_length=_STAGING_COPY_BATCH_SIZE)
    )
    async for batch in stream:
        rows = batch.to_pylist()
        records = [
            _StagingChunkRecord(
                id=r["id"],
                document_id=r["document_id"],
                content=r["content"],
                metadata=r["metadata"],
                order=r["order"],
            )
            for r in rows
        ]
        await staging.add(records)


async def _mark_phase1_complete(session: SingleDatabaseSession) -> None:
    """Create the marker table that designates staging as authoritative.

    Called after ``_populate_staging_table`` finishes. On crash recovery the
    marker's presence flips ``_rebuild_embed_only`` into resume mode.
    """
    db = session.store.db
    if _STAGING_MARKER_TABLE_NAME in (await db.list_tables()).tables:
        return
    marker = await db.create_table(
        _STAGING_MARKER_TABLE_NAME, schema=_StagingMarkerRecord
    )
    await marker.add([_StagingMarkerRecord(id="phase1_complete")])


async def _drop_staging_tables(session: SingleDatabaseSession) -> None:
    """Drop the marker first, then the staging table.

    Ordering matters: if a crash interrupts cleanup between the two drops,
    the next rebuild sees ``staging`` without ``marker`` and treats it as a
    partial phase 1 → drops staging harmlessly. The reverse order would
    leak a marker pointing at nothing.
    """
    db = session.store.db
    tables = (await db.list_tables()).tables
    if _STAGING_MARKER_TABLE_NAME in tables:
        await db.drop_table(_STAGING_MARKER_TABLE_NAME)
    if _STAGING_TABLE_NAME in tables:
        await db.drop_table(_STAGING_TABLE_NAME)


async def _read_chunks_from_staging(staging_table, document_id: str) -> list[Chunk]:
    """Read chunks for one document from the staging table.

    Only non-vector columns are selected: the staging table may have a
    different vector dimension than the new chunks table (during a dim
    migration), and we re-embed anyway.
    """
    rows = (
        await staging_table.query()
        .where(f"document_id = '{document_id}'")
        .select(["id", "document_id", "content", "metadata", "order"])
        .to_arrow()
    ).to_pylist()
    chunks: list[Chunk] = []
    for row in rows:
        chunks.append(
            Chunk(
                id=row["id"],
                document_id=row["document_id"],
                content=row["content"],
                metadata=json.loads(row["metadata"]),
                order=row["order"],
            )
        )
    chunks.sort(key=lambda c: c.order)
    return chunks


async def _rebuild_embed_only(
    session: SingleDatabaseSession,
    documents: list[Document],
    incomplete: IncompleteRebuildRecord,
    *,
    resume_from_staging: bool = False,
) -> AsyncGenerator[str, None]:
    """Re-embed all chunks without changing chunk boundaries.

    Two-phase pattern that keeps peak memory bounded regardless of corpus
    size and is idempotent across crashes:

    1. Stream-copy the chunks table's non-vector columns into a staging
       table, then write a marker row that designates staging as complete.
       LanceDB OSS does not support ``rename_table``, so the staging copy
       is the only safe way to preserve chunk identity while the live
       ``chunks`` table is dropped and recreated.
    2. Drop-and-recreate ``chunks`` with the current schema, then stream
       from staging one document at a time, re-embed in batches of
       ``embeddings.batch_size``, and flush to the new chunks table every
       ``_REBUILD_BATCH_SIZE`` documents.

    Cleanup runs only on success: a crash anywhere in phase 2 leaves both
    staging and marker in place so the next rebuild can re-enter phase 2
    via ``resume_from_staging=True``. The order of the success cleanup —
    drop marker before staging — keeps an interruption between the two
    drops recoverable: the next rebuild sees staging without marker and
    treats it as a partial phase 1, which is harmless because phase 2 has
    already finished writing the new chunks table.
    """
    from haiku.rag.embeddings import contextualize, embed_chunks

    db = session.store.db
    embedder = session.chunk_repository.embedder

    if not resume_from_staging:
        # Phase 1: copy chunks into staging, then mark it complete. After the
        # marker exists, a crash will resume phase 2 from staging.
        await _populate_staging_table(session)
        await _mark_phase1_complete(session)

    # Recreate the chunks table fresh (idempotent; handles vector-dim
    # changes and discards any partial new chunks from a prior crashed
    # phase 2).
    await _recreate_chunks_table(session, incomplete)

    staging_table = await db.open_table(_STAGING_TABLE_NAME)

    pending_records: list[ChunkRecordBase] = []
    yielded_docs: set[str] = set()

    for doc in documents:
        assert doc.id is not None
        chunks = await _read_chunks_from_staging(staging_table, doc.id)
        if not chunks:
            continue

        # Re-attach picture bytes stripped by the staging copy so picture
        # chunks route through embed_image rather than being text-embedded.
        # Bytes live in document_items (embed-only never touches that table).
        if embedder.supports_images:
            picture_data = await session.document_item_repository.get_all_picture_data(
                doc.id
            )
            for chunk in chunks:
                if "picture" not in (chunk.metadata.get("labels") or []):
                    continue
                refs = chunk.metadata.get("doc_item_refs") or []
                data = next((picture_data[r] for r in refs if r in picture_data), None)
                if data is not None:
                    chunk._picture_data = data
                else:
                    logger.warning(
                        "Document %s picture chunk %s has no recoverable bytes; "
                        "embedding its caption as text.",
                        doc.id,
                        chunk.id,
                    )

        content_fts_list = contextualize(chunks)
        embedded_chunks = await embed_chunks(chunks, embedder, session.config)

        for chunk, content_fts, embedded in zip(
            chunks, content_fts_list, embedded_chunks
        ):
            assert chunk.id is not None
            assert chunk.document_id is not None
            assert embedded.embedding is not None
            pending_records.append(
                session.store.ChunkRecord(
                    id=chunk.id,
                    document_id=chunk.document_id,
                    content=chunk.content,
                    content_fts=content_fts,
                    metadata=json.dumps(chunk.metadata),
                    order=chunk.order,
                    vector=embedded.embedding,
                )
            )

        yielded_docs.add(doc.id)
        # Yield per-doc for progress reporting; the actual write batches up
        # to _REBUILD_BATCH_SIZE docs. If the process is interrupted between
        # yield and the next flush, the next rebuild resumes phase 2 from
        # the staging table and redoes the batch.
        yield doc.id

        if len(yielded_docs) % _REBUILD_BATCH_SIZE == 0 and pending_records:
            await session.store.chunks_table.add(pending_records)
            await ensure_indexes(session.store.chunks_table, "chunks")
            pending_records = []

    if pending_records:
        await session.store.chunks_table.add(pending_records)
        await ensure_indexes(session.store.chunks_table, "chunks")

    # Phase 2 finished. Drop the recovery state — marker first so a crash
    # between the two drops leaves only staging behind, which the next
    # rebuild discards harmlessly.
    await _drop_staging_tables(session)

    for doc in documents:
        if doc.id and doc.id not in yielded_docs:
            yield doc.id


async def _flush_rebuild_batch(
    session: SingleDatabaseSession,
    documents: list[Document],
    chunks: list[Chunk],
    *,
    document_columns: tuple[str, ...],
) -> None:
    """Batch write documents and chunks during rebuild.

    Replaces the chunks of ``documents`` with ``chunks`` and writes only
    ``document_columns`` of each ``documents`` row, none when empty. Also
    repopulates document items from the stored docling document.

    The batch is one write transaction: a failure restores every table to
    what it held before, and the documents outside the batch are untouched.
    Nothing in it may take the store's write lock again, so callers rebuild
    indexes and yield only after it returns.
    """
    from haiku.rag.store.schema import DocumentMetaRecord

    if not documents:
        return

    now = datetime.now(UTC).isoformat()
    document_ids = [doc.id for doc in documents if doc.id is not None]

    async with session.store.write_transaction():
        await session.chunk_repository.delete_by_document_ids(document_ids)

        if document_columns:
            table = session.store.documents_table
            schema = await table.schema()
            columns = ("id", *document_columns)
            rows = [{c: getattr(doc, c) for c in columns} for doc in documents]
            source = pa.Table.from_pylist(
                rows, schema=pa.schema([schema.field(c) for c in columns])
            )
            # Update-only: a partial source with an insert branch is rejected.
            # The indexed plan holds the blobs in lance's query memory pool, unspillable.
            await (
                table.merge_insert("id")
                .when_matched_update_all()
                .use_index(False)
                .execute(source)
            )

        meta_records = []
        for doc in documents:
            assert doc.id is not None
            meta_records.append(
                DocumentMetaRecord(
                    id=doc.id,
                    uri=doc.uri,
                    title=doc.title,
                    metadata=json.dumps(doc.metadata),
                    created_at=doc.created_at.isoformat() if doc.created_at else now,
                    updated_at=now,
                )
            )

        await (
            session.store.document_meta_table.merge_insert("id")
            .when_matched_update_all()
            .when_not_matched_insert_all()
            .execute(meta_records)
        )

        # Batch create all chunks (single LanceDB version)
        if chunks:
            await session.chunk_repository.create(chunks)

        # Repopulate document items from stored docling data. The stored docling
        # blob has had its picture URIs stripped (compress_docling_split), so
        # re-extracting from it would lose picture_data — snapshot the existing
        # bytes per document and merge them back.
        # Lance holds about an add's pictures past the write, so items are added
        # whenever the whole documents gathered reach _ITEMS_WRITE_BYTES of them.
        items_repo = session.document_item_repository
        replaced = [doc for doc in documents if doc.docling_document is not None]
        existing_picture_data = await items_repo.get_all_picture_data_grouped(
            [doc.id for doc in replaced if doc.id is not None]
        )
        await items_repo.delete_by_document_ids(list(existing_picture_data))
        pending: list[DocumentItem] = []
        pending_bytes = 0
        for doc in replaced:
            assert doc.id is not None
            docling_doc = doc.get_docling_document()
            assert docling_doc is not None
            items = extract_items(
                doc.id,
                docling_doc,
                existing_picture_data=existing_picture_data.pop(doc.id),
            )
            pending.extend(items)
            pending_bytes += sum(len(i.picture_data or b"") for i in items)
            if pending_bytes >= _ITEMS_WRITE_BYTES:
                await items_repo.create_all(pending)
                pending, pending_bytes = [], 0
        await items_repo.create_all(pending)


async def _rebuild_rechunk(
    session: SingleDatabaseSession, documents: list[Document]
) -> AsyncGenerator[str, None]:
    """Re-chunk and re-embed each document from its stored docling blob."""
    from haiku.rag.embeddings import embed_chunks

    pending_chunks: list[Chunk] = []
    pending_docs: list[Document] = []
    embedder = session.store.embedder

    async for doc in _hydrate(session, documents):
        assert doc.id is not None
        docling_document = doc.get_docling_document()
        if docling_document is None:
            raise ValueError(
                f"Document {doc.id} has no stored docling document; rechunk "
                "requires it. Run a full rebuild (without --rechunk) instead."
            )

        # Stored blob has stripped picture URIs; pass the snapshot so
        # build_picture_chunks (inside chunk()) can recover the bytes.
        existing_picture_data = (
            await session.document_item_repository.get_all_picture_data(doc.id)
            if embedder.supports_images
            else None
        )
        chunks = await chunk_document(
            session,
            docling_document,
            existing_picture_data=existing_picture_data,
            document_id=doc.id,
        )
        embedded_chunks = await embed_chunks(chunks, embedder, session.config)

        for order, chunk in enumerate(embedded_chunks):
            chunk.document_id = doc.id
            chunk.order = order

        pending_chunks.extend(embedded_chunks)
        pending_docs.append(doc)

        # Documents are reported once their batch is written, so an interrupted
        # run has written every document it reported.
        if len(pending_docs) >= _REBUILD_BATCH_SIZE:
            await _flush_rebuild_batch(
                session, pending_docs, pending_chunks, document_columns=()
            )
            for written in pending_docs:
                assert written.id is not None
                yield written.id
            pending_chunks = []
            pending_docs = []

    if pending_docs:
        await _flush_rebuild_batch(
            session, pending_docs, pending_chunks, document_columns=()
        )
        for written in pending_docs:
            assert written.id is not None
            yield written.id


def _apply_descriptions_sync(
    docling_doc: "DoclingDocument", doc: Document, descriptions: dict[str, str]
) -> int:
    """Patch picture descriptions into the docling document and re-compress.

    Updates only docling_document — set_docling would also overwrite
    docling_pages by routing through compress_docling_split, which
    extracts pages from the in-memory JSON and finds none (the pages
    blob is stored separately and is not loaded by get_docling_document).
    That would silently destroy page rasters for every doc with at
    least one undescribed picture.
    """
    for pic in docling_doc.pictures:
        text = descriptions.get(pic.self_ref)
        if not text:
            continue
        if pic.meta is None:
            pic.meta = PictureMeta()
        pic.meta.description = DescriptionMetaField(text=text)

    structure_bytes, _ = compress_docling_split(docling_doc.model_dump(mode="json"))
    doc.docling_document = structure_bytes
    doc.docling_version = docling_doc.version
    return len(descriptions)


async def _patch_picture_descriptions(
    session: SingleDatabaseSession, doc: Document
) -> int:
    """Run the VLM against pictures lacking a description, patch the docling
    blob in-place. Returns the number of newly described pictures.
    Pictures that already carry ``meta.description.text`` are skipped, so the
    operation is safe to re-run after a partial failure.
    """
    from haiku.rag.providers.picture_description import describe_pictures

    assert doc.id is not None
    docling_doc = doc.get_docling_document()
    if docling_doc is None or not docling_doc.pictures:
        return 0

    needs_description: list[str] = []
    for pic in docling_doc.pictures:
        existing = (
            pic.meta.description.text if pic.meta and pic.meta.description else None
        )
        if not (existing and existing.strip()):
            needs_description.append(pic.self_ref)

    if not needs_description:
        return 0

    bytes_by_ref = await session.document_item_repository.get_pictures_for_chunk(
        doc.id, needs_description
    )
    if not bytes_by_ref:
        logger.warning(
            "Document %s has %d pictures missing descriptions but no stored "
            "picture bytes — skipping. Run a full rebuild from source to "
            "recover the bytes.",
            doc.id,
            len(needs_description),
        )
        return 0

    descriptions = await describe_pictures(bytes_by_ref, config=session.config)

    if not descriptions:
        return 0

    return await asyncio.to_thread(
        _apply_descriptions_sync, docling_doc, doc, descriptions
    )


async def _rebuild_descriptions(
    session: SingleDatabaseSession, documents: list[Document]
) -> AsyncGenerator[str, None]:
    """Run the VLM over already-stored picture bytes, patch descriptions into
    the docling blob, then re-chunk + re-embed.

    Skips the docling parse entirely (the blob is already there); only the VLM
    cost remains. Idempotent: pictures whose ``meta.description.text`` is
    already populated are not re-described.
    """
    from haiku.rag.embeddings import embed_chunks

    pending_chunks: list[Chunk] = []
    pending_docs: list[Document] = []
    embedder = session.store.embedder

    described_total = 0
    async for doc in _hydrate(session, documents):
        assert doc.id is not None
        docling_document = doc.get_docling_document()
        if docling_document is None:
            raise ValueError(
                f"Document {doc.id} has no stored docling document; "
                "rebuild --descriptions requires it. Run a full rebuild instead."
            )

        n = await _patch_picture_descriptions(session, doc)
        described_total += n
        # Use the (possibly patched) docling document for chunking.
        docling_document = doc.get_docling_document()
        assert docling_document is not None

        existing_picture_data = (
            await session.document_item_repository.get_all_picture_data(doc.id)
            if embedder.supports_images
            else None
        )
        chunks = await chunk_document(
            session,
            docling_document,
            existing_picture_data=existing_picture_data,
            document_id=doc.id,
        )
        embedded_chunks = await embed_chunks(chunks, embedder, session.config)

        for order, chunk in enumerate(embedded_chunks):
            chunk.document_id = doc.id
            chunk.order = order

        pending_chunks.extend(embedded_chunks)
        pending_docs.append(doc)

        if len(pending_docs) >= _REBUILD_BATCH_SIZE:
            await _flush_rebuild_batch(
                session,
                pending_docs,
                pending_chunks,
                document_columns=_DESCRIPTION_COLUMNS,
            )
            for written in pending_docs:
                assert written.id is not None
                yield written.id
            pending_chunks = []
            pending_docs = []

    if pending_docs:
        await _flush_rebuild_batch(
            session, pending_docs, pending_chunks, document_columns=_DESCRIPTION_COLUMNS
        )
        for written in pending_docs:
            assert written.id is not None
            yield written.id

    logger.info(
        "rebuild --descriptions: %d new picture descriptions added across %d documents",
        described_total,
        len(documents),
    )


async def _rebuild_full(
    session: SingleDatabaseSession, documents: list[Document]
) -> AsyncGenerator[str, None]:
    """Full rebuild: re-convert from source, re-chunk, re-embed."""
    from haiku.rag.embeddings import embed_chunks

    pending_chunks: list[Chunk] = []
    pending_docs: list[Document] = []
    converter = get_converter(session.config)
    embedder = session.store.embedder

    written_ids: set[str] = set()

    # Parents first: a parent's refresh rebuilds its attachments from their own bytes.
    for light_doc in sorted(
        documents, key=lambda d: bool((d.metadata or {}).get("parent_uri"))
    ):
        assert light_doc.id is not None
        if light_doc.id in written_ids:
            continue
        # An attachment's URI resolves to its parent's file, never its own payload.
        source = None if (light_doc.metadata or {}).get("parent_uri") else light_doc.uri

        # Try to rebuild from source if available — uses the light listing
        # directly, no need to load the stored content/blobs first.
        if source and check_source_accessible(source):
            # The refresh writes through the database, not the batch buffer, so
            # anything pending has to land first. Its transaction is over by
            # the time the refresh takes the same lock.
            if pending_docs:
                await _flush_rebuild_batch(
                    session,
                    pending_docs,
                    pending_chunks,
                    document_columns=_FULL_FALLBACK_COLUMNS,
                )
                for written in pending_docs:
                    assert written.id is not None
                    yield written.id
                pending_chunks = []
                pending_docs = []

            # force=True: the source bytes are usually unchanged, and the
            # point of a FULL rebuild is to re-convert them anyway. Updates
            # in place, so a failure here cannot cost the document.
            refreshed: set[str] = set()
            failure: Exception | None = None
            try:
                await create_document_from_source(
                    session,
                    source=source,
                    metadata=light_doc.metadata or {},
                    force=True,
                    written_ids=refreshed,
                )
            except Exception as e:
                failure = e
            for doc_id in refreshed:
                yield doc_id
            written_ids |= refreshed

            if failure is not None and light_doc.id in refreshed:
                logger.warning(
                    "Rebuilding %s from source failed (%s)", light_doc.uri, failure
                )
            elif failure is not None:
                logger.warning(
                    "Rebuilding %s from source failed (%s), "
                    "falling back to stored content",
                    light_doc.uri,
                    failure,
                )
            if light_doc.id in refreshed:
                continue
        elif source:
            logger.warning(
                "Source missing for %s, re-embedding from content", light_doc.uri
            )

        # Fallback: rebuild from stored content; set_docling replaces both blobs.
        doc = await session.document_repository.get_by_id(light_doc.id)
        if doc is None:
            continue
        assert doc.id is not None

        docling_document = await converter.convert_text(doc.content, format="md")
        chunks = await chunk_document(session, docling_document)
        embedded_chunks = await embed_chunks(chunks, embedder, session.config)

        doc.set_docling(docling_document)

        for order, chunk in enumerate(embedded_chunks):
            chunk.document_id = doc.id
            chunk.order = order

        pending_chunks.extend(embedded_chunks)
        pending_docs.append(doc)

        if len(pending_docs) >= _REBUILD_BATCH_SIZE:
            await _flush_rebuild_batch(
                session,
                pending_docs,
                pending_chunks,
                document_columns=_FULL_FALLBACK_COLUMNS,
            )
            for written in pending_docs:
                assert written.id is not None
                yield written.id
            pending_chunks = []
            pending_docs = []

    if pending_docs:
        await _flush_rebuild_batch(
            session,
            pending_docs,
            pending_chunks,
            document_columns=_FULL_FALLBACK_COLUMNS,
        )
        for written in pending_docs:
            assert written.id is not None
            yield written.id
